-- ============================================================
-- PENDING MIGRATION: the panel host is a managed node
--
-- This file is not numbered yet. Rename it into the sequence as
-- 0NN_local_node.sql when it is folded in; nothing here depends on the number.
--
-- WHAT IT IS FOR
--
-- VKAI Panel was built as a control plane for a fleet: the panel here, agents
-- there, every operation carried over mutual TLS. Nothing was ever wrong with
-- that, but it left the machine the panel was installed on managing nothing.
-- One command installs the panel, an administrator signs in, and to create a
-- single website they have to find a second machine. aaPanel installs onto a
-- VPS and manages that VPS; this migration is the schema half of matching it.
--
-- After it, the panel host holds a row in `servers` like any other node, and
-- this table is what says that one of those rows is the machine the panel is
-- running on - and carries the evidence for the claim.
--
-- WHY A TABLE AND NOT COLUMNS ON `servers`
--
-- repository/server.go reads servers with `SELECT *` into models.Server, so a
-- column added there breaks every server query until that struct changes in the
-- same commit. A separate table is additive: an installation that has not run
-- this migration keeps working, and the code degrades to "there is no local
-- node" rather than to "there are no servers". It also puts the local marker
-- somewhere the operator-facing PUT /servers/:id cannot reach - servers.role
-- and servers.status are free-form and editable, and a flag that decides
-- whether the panel runs a command locally must not be one an API call can set.
--
-- THE IDENTITY
--
-- The key is servers.id, which for this node is a UUID generated once at
-- registration and persisted at <EtcRoot>/node.json, 0600. Hostname and IP were
-- both rejected as the key because both change under a running installation and
-- either would fork one node into two rows on the next registration.
-- /etc/machine-id was rejected as the key because it is not ours: absent in
-- some containers, regenerated by some cloud images, carried along by a cloned
-- disk, and documented by systemd as a value that should not be exposed.
--
-- It is kept instead as a witness, hashed, in machine_fingerprint. See
-- core/internal/localnode for the full argument.
-- ============================================================

-- One row per node that some panel process claims as the machine it runs on.
-- Absence of a row means the node is remote, and every operation on it goes
-- through the agent transport.
CREATE TABLE IF NOT EXISTS server_local_node (
    server_id            UUID PRIMARY KEY REFERENCES servers(id) ON DELETE CASCADE,

    -- Salted SHA-256 of /etc/machine-id (or /var/lib/dbus/machine-id) as it was
    -- when this node was registered. The raw machine id is never stored: it is
    -- hashed so that a database dump does not carry it.
    --
    -- NULL means no machine id could be read on that host. The witness is then
    -- unavailable rather than negative, and the panel says so instead of
    -- inventing a fingerprint that would prove nothing.
    machine_fingerprint  VARCHAR(64),

    -- 'machine-id' or 'dbus-machine-id': which file the witness came from, so
    -- that an operator reading a mismatch knows what changed underneath it.
    fingerprint_source   VARCHAR(32),

    registered_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- The last time a panel process stood on this machine and proved it. It is
    -- written by the running panel, not by the installer, which is what keeps
    -- it from being a claim made once and true forever.
    last_verified_at     TIMESTAMP WITH TIME ZONE,

    -- The last time verification failed, and why. A row with a recent value
    -- here is a node the panel refuses to treat as local: the usual cause is a
    -- database restored onto a different machine.
    last_mismatch_at     TIMESTAMP WITH TIME ZONE,
    last_mismatch_reason TEXT,

    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- The recovery lookup: node.json was lost, a new identity would fork the node
-- into a second row, so registration first asks whether some existing row was
-- registered by this same machine.
CREATE INDEX IF NOT EXISTS idx_server_local_node_fingerprint
    ON server_local_node(machine_fingerprint);

-- There is deliberately NO constraint limiting this table to one row. It is
-- tempting - one panel, one host - but a clustered installation is two panel
-- processes on two machines sharing one database (see 014_cluster_ha.sql), and
-- each of them is local to its own host. Correctness does not come from there
-- being a single row; it comes from each panel matching a row against the node
-- identity and machine witness of the machine it is actually standing on.

COMMENT ON TABLE server_local_node IS
    'Which servers rows are the machine a panel process is running on, and the evidence for it. A node listed here can be operated on without the agent transport.';
COMMENT ON COLUMN server_local_node.machine_fingerprint IS
    'Salted SHA-256 of the host machine id at registration. NULL when the host has no machine id file. The raw machine id is never stored.';
COMMENT ON COLUMN server_local_node.last_verified_at IS
    'Last time a panel process proved it was standing on this machine. Stale means the panel has not run here recently, not that the node is healthy.';

-- ============================================================
-- WHAT THIS MIGRATION DOES NOT DO
--
-- It does not insert a row. The panel host registers itself when the API
-- process starts, or when the installer or the CLI calls the same idempotent
-- path, because the facts written into that row - os, kernel, cpu_cores,
-- ram_total, disk_total - have to be measured on the running system and a
-- migration cannot measure anything.
--
-- It does not touch servers.agent_status. A local node reuses the existing
-- 'online' and 'offline' values rather than adding a third: what makes it local
-- is this table, and every consumer that already understands the two values
-- keeps working.
-- ============================================================
