package acme

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"
)

// Default tuning. Every value can be overridden through Config.
const (
	defaultTimeout         = 5 * time.Minute
	defaultPollInterval    = 2 * time.Second
	defaultMaxPollInterval = 15 * time.Second
	defaultHTTPTimeout     = 30 * time.Second
	defaultUserAgent       = "vkai-panel-acme/1.0 (+https://github.com/hitechcloud-vietnam/vkai-panel)"

	// maxBodySize caps how much of a CA response is read. ACME resources are
	// small; anything larger is a misconfigured proxy rather than a CA.
	maxBodySize = 4 << 20

	// contentTypeJOSE is the media type every signed ACME request carries.
	contentTypeJOSE = "application/jose+json"
)

// ChallengeSolver publishes and withdraws an HTTP-01 challenge response.
//
// Present must arrange that a GET of
//
//	http://<identifier>/.well-known/acme-challenge/<token>
//
// returns keyAuth as a plain body on port 80. CleanUp must remove it again and
// is called for every token that was presented, including when issuance failed.
//
// The interface exists because the panel does not own port 80: on a machine
// hosting customer websites that port belongs to nginx, so the caller decides
// whether to drop the token into an existing webroot or to bind the port for the
// few seconds validation takes.
type ChallengeSolver interface {
	// Present publishes keyAuth under the given challenge token.
	Present(token, keyAuth string) error

	// CleanUp withdraws whatever Present published for the token.
	CleanUp(token string) error
}

// Config configures a Client.
type Config struct {
	// DirectoryURL is the ACME directory to talk to. Empty means
	// LetsEncryptProduction, or LetsEncryptStaging when Staging is set.
	DirectoryURL string

	// Staging selects LetsEncryptStaging when DirectoryURL is empty. It is
	// ignored when DirectoryURL is set explicitly.
	Staging bool

	// AccountDir is the directory holding the ES256 account key and the account
	// metadata. Both are written with mode 0600 and the directory is created
	// with mode 0700 when missing. Required.
	AccountDir string

	// Email is an optional contact address registered with the account. It is
	// sent as "mailto:<Email>".
	Email string

	// AgreeTOS must be true: the CA rejects newAccount without
	// termsOfServiceAgreed, so refusing to set it can only produce a confusing
	// failure later.
	AgreeTOS bool

	// HTTPClient issues the requests. Nil means an internal client with a 30
	// second per-request timeout.
	HTTPClient *http.Client

	// UserAgent overrides the User-Agent header.
	UserAgent string

	// Timeout bounds a whole Obtain call, covering every poll and retry. Zero
	// means five minutes.
	Timeout time.Duration

	// PollInterval is the first delay between status polls. Zero means two
	// seconds.
	PollInterval time.Duration

	// MaxPollInterval caps the exponential growth of the poll delay. Zero means
	// fifteen seconds.
	MaxPollInterval time.Duration
}

// Client is an ACME v2 client bound to one account key and one CA.
//
// A Client is safe for concurrent use, but a single ACME account is not a
// parallel-issuance mechanism: run one Obtain at a time.
type Client struct {
	cfg          Config
	directoryURL string
	httpClient   *http.Client
	userAgent    string

	// key is the ES256 account key, loaded or generated by New.
	key *ecdsa.PrivateKey

	mu      sync.Mutex
	dir     *Directory
	account *Account
	nonces  []string
}

// New loads or creates the account key in cfg.AccountDir and returns a Client.
// It performs no network I/O; the directory is fetched lazily on first use.
func New(cfg Config) (*Client, error) {
	if cfg.AccountDir == "" {
		return nil, errors.New("acme: Config.AccountDir is required")
	}
	if !cfg.AgreeTOS {
		return nil, errors.New("acme: Config.AgreeTOS must be true, the CA rejects newAccount without termsOfServiceAgreed")
	}

	directoryURL := cfg.DirectoryURL
	if directoryURL == "" {
		if cfg.Staging {
			directoryURL = LetsEncryptStaging
		} else {
			directoryURL = LetsEncryptProduction
		}
	}

	key, err := loadOrCreateAccountKey(cfg.AccountDir)
	if err != nil {
		return nil, err
	}

	httpClient := cfg.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{Timeout: defaultHTTPTimeout}
	}
	userAgent := cfg.UserAgent
	if userAgent == "" {
		userAgent = defaultUserAgent
	}

	return &Client{
		cfg:          cfg,
		directoryURL: directoryURL,
		httpClient:   httpClient,
		userAgent:    userAgent,
		key:          key,
	}, nil
}

// DirectoryURL reports the directory this client talks to.
func (c *Client) DirectoryURL() string { return c.directoryURL }

// AccountKeyThumbprint returns the RFC 7638 thumbprint of the account key. A
// caller that publishes challenges itself can build key authorizations from it
// without going through the solver interface.
func (c *Client) AccountKeyThumbprint() (string, error) {
	return thumbprint(&c.key.PublicKey)
}

// KeyAuthorization returns the RFC 8555 section 8.1 key authorization for a
// challenge token under this client's account key.
func (c *Client) KeyAuthorization(token string) (string, error) {
	return keyAuthorization(token, &c.key.PublicKey)
}

// Directory fetches and caches the CA's directory resource. Meta.Profiles tells
// the caller which certificate profiles the CA offers, which is what a caller
// needs before asking for one: Let's Encrypt issues for IP identifiers only
// under ProfileShortLived.
func (c *Client) Directory(ctx context.Context) (*Directory, error) {
	c.mu.Lock()
	cached := c.dir
	c.mu.Unlock()
	if cached != nil {
		return cached, nil
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.directoryURL, nil)
	if err != nil {
		return nil, fmt.Errorf("acme: build directory request: %w", err)
	}
	resp, err := c.roundTrip(req)
	if err != nil {
		return nil, err
	}
	if resp.Status != http.StatusOK {
		return nil, resp.toError(c.directoryURL)
	}
	var dir Directory
	if err := json.Unmarshal(resp.Body, &dir); err != nil {
		return nil, fmt.Errorf("acme: parse directory from %s: %w", c.directoryURL, err)
	}
	if dir.NewNonce == "" || dir.NewAccount == "" || dir.NewOrder == "" {
		return nil, fmt.Errorf("acme: directory at %s is missing newNonce, newAccount or newOrder", c.directoryURL)
	}

	c.mu.Lock()
	c.dir = &dir
	c.mu.Unlock()
	return &dir, nil
}

// Profiles returns the certificate profiles advertised in meta.profiles. An
// empty result means the CA does not support profile selection, in which case
// the profile argument to Obtain must be empty.
func (c *Client) Profiles(ctx context.Context) (Profiles, error) {
	dir, err := c.Directory(ctx)
	if err != nil {
		return nil, err
	}
	return dir.Meta.Profiles, nil
}

// Account registers the account key with the CA, or reuses the account URL
// stored in AccountDir from an earlier run. It is idempotent and safe to call
// repeatedly; Obtain calls it itself.
func (c *Client) Account(ctx context.Context) (*Account, error) {
	c.mu.Lock()
	cached := c.account
	c.mu.Unlock()
	if cached != nil {
		return cached, nil
	}

	dir, err := c.Directory(ctx)
	if err != nil {
		return nil, err
	}

	contact := contactList(c.cfg.Email)

	// Reuse a stored account URL when it belongs to this same CA. A staging
	// account is worthless against production, so a directory mismatch forces a
	// fresh newAccount rather than a request the CA would reject as unknown.
	meta, err := loadAccountMeta(c.cfg.AccountDir)
	if err != nil {
		return nil, err
	}
	if meta != nil && meta.Kid != "" && (meta.DirectoryURL == "" || meta.DirectoryURL == c.directoryURL) {
		account := &Account{URL: meta.Kid, Contact: meta.Contact, Key: c.key}
		c.mu.Lock()
		c.account = account
		c.mu.Unlock()
		return account, nil
	}

	payload, err := json.Marshal(newAccountRequest{
		TermsOfServiceAgreed: true,
		Contact:              contact,
	})
	if err != nil {
		return nil, fmt.Errorf("acme: marshal newAccount request: %w", err)
	}

	// newAccount is the one request signed with the full jwk: the CA cannot yet
	// know a kid for a key it has never seen.
	resp, err := c.post(ctx, dir.NewAccount, payload, true)
	if err != nil {
		return nil, err
	}
	if resp.Status != http.StatusCreated && resp.Status != http.StatusOK {
		return nil, resp.toError(dir.NewAccount)
	}
	location := resp.Header.Get("Location")
	if location == "" {
		return nil, fmt.Errorf("acme: newAccount response from %s has no Location header", dir.NewAccount)
	}
	var res accountResource
	if len(resp.Body) > 0 {
		if err := json.Unmarshal(resp.Body, &res); err != nil {
			return nil, fmt.Errorf("acme: parse newAccount response: %w", err)
		}
	}
	if res.Status == statusDeactivated || res.Status == statusRevoked {
		return nil, fmt.Errorf("acme: account %s is %s", location, res.Status)
	}

	account := &Account{URL: location, Contact: res.Contact, Key: c.key}
	if account.Contact == nil {
		account.Contact = contact
	}
	if err := saveAccountMeta(c.cfg.AccountDir, &accountMeta{
		Kid:          account.URL,
		Contact:      account.Contact,
		DirectoryURL: c.directoryURL,
	}); err != nil {
		return nil, err
	}

	c.mu.Lock()
	c.account = account
	c.mu.Unlock()
	return account, nil
}

// acmeResponse is one CA response, already read into memory.
type acmeResponse struct {
	Status int
	Header http.Header
	Body   []byte
}

// problem parses the body as an RFC 7807 problem document. It returns nil when
// the body is not a problem document.
func (r *acmeResponse) problem() *Problem {
	ct := r.Header.Get("Content-Type")
	if !strings.HasPrefix(ct, "application/problem+json") && len(r.Body) == 0 {
		return nil
	}
	var prob Problem
	if err := json.Unmarshal(r.Body, &prob); err != nil {
		return nil
	}
	if prob.Type == "" && prob.Detail == "" && prob.Title == "" && len(prob.Subproblems) == 0 {
		return nil
	}
	if prob.Status == 0 {
		prob.Status = r.Status
	}
	return &prob
}

// toError converts a failing response into the richest error available: a
// RateLimitError when the CA is throttling, the verbatim problem document
// otherwise, and a last-resort message carrying the truncated body when the CA
// sent something that is not a problem document at all.
func (r *acmeResponse) toError(url string) error {
	prob := r.problem()
	if r.Status == http.StatusTooManyRequests || (prob != nil && prob.IsRateLimited()) {
		wait, raw := parseRetryAfter(r.Header, time.Now())
		return &RateLimitError{
			Problem:          prob,
			RetryAfter:       wait,
			RetryAfterHeader: raw,
			StatusCode:       r.Status,
			URL:              url,
		}
	}
	if prob != nil {
		return prob
	}
	body := string(bytes.TrimSpace(r.Body))
	if len(body) > 512 {
		body = body[:512] + "..."
	}
	return fmt.Errorf("acme: unexpected HTTP %d from %s: %s", r.Status, url, body)
}

// roundTrip performs one HTTP request, reads the body and caches any
// Replay-Nonce the CA attached. Every response carries a usable nonce, so
// harvesting them here is what keeps the client from making a newNonce round
// trip before each request.
func (c *Client) roundTrip(req *http.Request) (*acmeResponse, error) {
	req.Header.Set("User-Agent", c.userAgent)
	if req.Header.Get("Accept") == "" {
		req.Header.Set("Accept", "application/json, application/problem+json, application/pem-certificate-chain")
	}

	httpResp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("acme: %s %s: %w", req.Method, req.URL, err)
	}
	defer httpResp.Body.Close()

	body, err := io.ReadAll(io.LimitReader(httpResp.Body, maxBodySize))
	if err != nil {
		return nil, fmt.Errorf("acme: read response from %s: %w", req.URL, err)
	}
	if nonce := httpResp.Header.Get("Replay-Nonce"); nonce != "" {
		c.pushNonce(nonce)
	}
	return &acmeResponse{Status: httpResp.StatusCode, Header: httpResp.Header, Body: body}, nil
}

// pushNonce caches a nonce. The cache is deliberately shallow: nonces expire and
// a large backlog only increases the chance of using a stale one.
func (c *Client) pushNonce(nonce string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if len(c.nonces) >= 8 {
		c.nonces = c.nonces[1:]
	}
	c.nonces = append(c.nonces, nonce)
}

// popNonce takes a cached nonce, returning "" when none is available.
func (c *Client) popNonce() string {
	c.mu.Lock()
	defer c.mu.Unlock()
	if len(c.nonces) == 0 {
		return ""
	}
	nonce := c.nonces[len(c.nonces)-1]
	c.nonces = c.nonces[:len(c.nonces)-1]
	return nonce
}

// clearNonces drops every cached nonce. Used after a badNonce rejection, since
// the rest of the cache was very likely issued in the same stale batch.
func (c *Client) clearNonces() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.nonces = nil
}

// fetchNonce performs a HEAD against newNonce and caches the result.
func (c *Client) fetchNonce(ctx context.Context) error {
	dir, err := c.Directory(ctx)
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodHead, dir.NewNonce, nil)
	if err != nil {
		return fmt.Errorf("acme: build newNonce request: %w", err)
	}
	resp, err := c.roundTrip(req)
	if err != nil {
		return err
	}
	if resp.Status != http.StatusOK && resp.Status != http.StatusNoContent {
		return resp.toError(dir.NewNonce)
	}
	if resp.Header.Get("Replay-Nonce") == "" {
		return fmt.Errorf("acme: newNonce at %s returned no Replay-Nonce header", dir.NewNonce)
	}
	return nil
}

// nonce returns a nonce, fetching a fresh one when the cache is empty.
func (c *Client) nonce(ctx context.Context) (string, error) {
	if nonce := c.popNonce(); nonce != "" {
		return nonce, nil
	}
	if err := c.fetchNonce(ctx); err != nil {
		return "", err
	}
	if nonce := c.popNonce(); nonce != "" {
		return nonce, nil
	}
	return "", errors.New("acme: no nonce available after newNonce")
}

// post sends a signed ACME request and retries exactly once on badNonce with a
// freshly fetched nonce, which is the recovery RFC 8555 section 6.5 prescribes.
// A second badNonce is a real fault and is returned to the caller.
func (c *Client) post(ctx context.Context, url string, payload []byte, useJWK bool) (*acmeResponse, error) {
	resp, err := c.postOnce(ctx, url, payload, useJWK)
	if err == nil {
		return resp, nil
	}

	var prob *Problem
	if !errors.As(err, &prob) || prob.Type != errBadNonce {
		return nil, err
	}

	c.clearNonces()
	if ferr := c.fetchNonce(ctx); ferr != nil {
		return nil, fmt.Errorf("acme: refresh nonce after badNonce from %s: %w (original error: %v)", url, ferr, err)
	}
	return c.postOnce(ctx, url, payload, useJWK)
}

// postOnce sends one signed ACME request without retrying.
//
// payload nil means POST-as-GET: the JWS carries an empty payload string, which
// is how RFC 8555 section 6.3 reads a resource that requires authentication.
func (c *Client) postOnce(ctx context.Context, url string, payload []byte, useJWK bool) (*acmeResponse, error) {
	nonce, err := c.nonce(ctx)
	if err != nil {
		return nil, err
	}

	header := protectedHeader{Alg: "ES256", Nonce: nonce, URL: url}
	if useJWK {
		jwk, err := publicJWK(&c.key.PublicKey)
		if err != nil {
			return nil, err
		}
		header.JWK = jwk
	} else {
		c.mu.Lock()
		account := c.account
		c.mu.Unlock()
		if account == nil || account.URL == "" {
			return nil, errors.New("acme: no account URL available, call Account before signing with kid")
		}
		header.Kid = account.URL
	}

	body, err := encodeJWS(c.key, header, payload)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("acme: build request for %s: %w", url, err)
	}
	req.Header.Set("Content-Type", contentTypeJOSE)

	resp, err := c.roundTrip(req)
	if err != nil {
		return nil, err
	}
	if resp.Status >= 400 {
		return nil, resp.toError(url)
	}
	return resp, nil
}
