#!/usr/bin/env node
/**
 * Writes the product version into the UI bundle.
 *
 * The single source of truth is the file VERSION at the repository root. The
 * browser cannot read a file at runtime, so the version has to be compiled into
 * the bundle; this script does that by generating src/lib/version.generated.ts,
 * which src/lib/brand.ts imports.
 *
 * The generated file is NOT committed (see .gitignore). It is written by the
 * "prebuild" / "predev" / "pretype-check" npm scripts, so every build, dev
 * server and type-check regenerates it from VERSION. A build that somehow skips
 * this script fails loudly at compile time with "Cannot find module
 * './version.generated'" instead of silently shipping a stale version.
 *
 * Usage:
 *   node scripts/gen-version.js            generate; fail if package.json drifted
 *   node scripts/gen-version.js --write    generate and fix package.json's version
 *   node scripts/gen-version.js --check    verify only; write nothing
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PANEL_DIR = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(PANEL_DIR, '..');
const VERSION_FILE = path.join(REPO_ROOT, 'VERSION');
const PACKAGE_JSON = path.join(PANEL_DIR, 'package.json');
const PACKAGE_LOCK = path.join(PANEL_DIR, 'package-lock.json');
const GENERATED_FILE = path.join(PANEL_DIR, 'src', 'lib', 'version.generated.ts');

// The subset of SemVer 2.0.0 the panel releases use, matching what
// core/internal/upgrade.ParseVersion accepts.
const SEMVER =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

function fail(message) {
  console.error(`gen-version: ${message}`);
  process.exit(1);
}

function readVersion() {
  let raw;
  try {
    raw = fs.readFileSync(VERSION_FILE, 'utf8');
  } catch (err) {
    fail(
      `cannot read ${path.relative(PANEL_DIR, VERSION_FILE)}: ${err.message}\n` +
        'The repository root VERSION file is the single source of truth for the ' +
        'product version. The UI cannot be built without it.'
    );
  }
  const version = raw.trim();
  if (!SEMVER.test(version)) {
    fail(`VERSION contains ${JSON.stringify(version)}, which is not a semantic version (MAJOR.MINOR.PATCH).`);
  }
  return version;
}

function renderGenerated(version) {
  return `// Code generated from the repository VERSION file by panel/scripts/gen-version.js.
// DO NOT EDIT and DO NOT COMMIT: this file is regenerated by the prebuild,
// predev and pretype-check npm scripts, and is listed in .gitignore.
//
// src/lib/brand.ts is the only file that should import it.

export const generatedVersion = '${version}';
`;
}

function syncPackageJson(version, mode) {
  const raw = fs.readFileSync(PACKAGE_JSON, 'utf8');
  const pkg = JSON.parse(raw);
  if (pkg.version === version) {
    return false;
  }
  if (mode !== 'write') {
    fail(
      `panel/package.json says "version": ${JSON.stringify(pkg.version)} but ` +
        `VERSION says ${JSON.stringify(version)}.\n` +
        'The two must agree. Fix it with "make sync-version" (or ' +
        '"node scripts/gen-version.js --write" from panel/).'
    );
  }
  pkg.version = version;
  fs.writeFileSync(PACKAGE_JSON, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');
  return true;
}

/**
 * package-lock.json records the root package's version too. npm rewrites it from
 * package.json on the next install, and "npm ci" does not check it, so a stale
 * value breaks nothing - it is just one more place claiming to know the version.
 * Keeping it in step is best effort: never fail a build over a file npm owns.
 */
function syncPackageLock(version, mode) {
  let raw;
  try {
    raw = fs.readFileSync(PACKAGE_LOCK, 'utf8');
  } catch {
    return false;
  }

  let lock;
  try {
    lock = JSON.parse(raw);
  } catch (err) {
    console.warn(`gen-version: cannot parse package-lock.json (${err.message}); leaving it alone.`);
    return false;
  }

  const root = lock.packages && lock.packages[''];
  const stale = lock.version !== version || (root && root.version !== version);
  if (!stale) {
    return false;
  }
  if (mode !== 'write') {
    console.warn(
      `gen-version: package-lock.json still says ${JSON.stringify(lock.version)}; ` +
        'run "make sync-version" to update it.'
    );
    return false;
  }

  lock.version = version;
  if (root) root.version = version;
  fs.writeFileSync(PACKAGE_LOCK, `${JSON.stringify(lock, null, 2)}\n`, 'utf8');
  return true;
}

function main() {
  const args = process.argv.slice(2);
  const mode = args.includes('--check') ? 'check' : args.includes('--write') ? 'write' : 'generate';

  const version = readVersion();
  const changedPackageJson = syncPackageJson(version, mode);
  const changedPackageLock = syncPackageLock(version, mode);

  const wanted = renderGenerated(version);
  let current = null;
  try {
    current = fs.readFileSync(GENERATED_FILE, 'utf8');
  } catch {
    current = null;
  }

  if (mode === 'check') {
    if (current !== wanted) {
      fail(
        `${path.relative(REPO_ROOT, GENERATED_FILE)} is missing or stale for version ${version}.\n` +
          'Run "make sync-version", or build the UI, which regenerates it.'
      );
    }
    console.log(`gen-version: ${version} - everything is in sync.`);
    return;
  }

  if (current !== wanted) {
    fs.mkdirSync(path.dirname(GENERATED_FILE), { recursive: true });
    fs.writeFileSync(GENERATED_FILE, wanted, 'utf8');
  }

  const notes = [];
  if (changedPackageJson) notes.push('package.json updated');
  if (changedPackageLock) notes.push('package-lock.json updated');
  console.log(
    `gen-version: ${version} -> ${path.relative(REPO_ROOT, GENERATED_FILE)}` +
      (notes.length ? ` (${notes.join(', ')})` : '')
  );
}

main();
