// Package agentpki is the panel's internal certificate authority for the
// panel-to-agent control channel.
//
// # Why this package exists
//
// Before it, the channel was a single static string. One VKAI_AGENT_TOKEN was
// generated by the installer, written into /vkai-panel/etc/.env, and shipped to
// every managed server. The agent compared it with "!=" and then ran whatever
// command the caller asked for, as root. Anyone who read that string once -
// from a config file, an environment dump, a log line, or the wire, since none
// of it was encrypted - owned every server the panel managed. That is the
// single worst property the product had.
//
// # The model
//
//	panel host                          managed server
//	----------                          --------------
//	CA key + CA cert  ---- issues --->  agent server/client certificate
//	panel client certificate            (24h, renewed at half life)
//
// The rules:
//
//   - The CA key is generated on the panel host and never leaves it. Nothing in
//     this package reads or writes it outside the panel SSL directory, and it
//     is written 0600.
//   - The panel issues itself one client certificate and issues each enrolled
//     agent one certificate that is valid for both server and client use: the
//     agent presents it as a server when the panel dials in, and proves
//     possession of the same key when it calls the panel's enrolment, renewal
//     and status endpoints.
//   - Nobody is trusted by host name or IP address. Customer servers change
//     addresses, get rebuilt behind NAT and move between providers, so
//     verification is: chain to this CA, carry the expected role, and be the
//     specific certificate this panel issued to this agent. See VerifyAgentPeer
//     and VerifyPanelPeer.
//
// # Enrolment
//
// A one-time token, minted by an administrator and pasted into the agent
// installer, is exchanged exactly once for a certificate and is then dead. The
// token carries a fingerprint of the CA public key, so the agent can tell that
// the CA certificate it receives in the reply is the one the operator meant -
// trust on paste, rather than trust on first sight.
//
// # Rotation and its overlap window
//
// Certificates are short (24 hours by default) and the agent renews at half
// life. A renewal never invalidates the certificate the agent is currently
// using: the previous certificate stays acceptable for OverlapWindow after it
// was superseded (and never past its own expiry). An agent that renews and then
// loses the answer - a dropped connection, a crash before the write, a reverted
// snapshot - keeps working with what it already has and simply renews again.
//
// # Revocation, and what it does not do
//
// Revocation is a serial deny list checked on every handshake and on every
// signed request. It takes effect on the next connection, not at the next
// expiry, and no CRL fetch or OCSP responder is involved.
//
// Its honest limits:
//
//   - It is authoritative on the panel. An agent learns about revoked panel
//     certificates only when the panel next reaches it and pushes the list, so
//     an agent that is unreachable keeps accepting a revoked panel client
//     certificate until it is reachable again. The mitigation is the 24 hour
//     certificate lifetime: an unreachable agent stops accepting the old panel
//     certificate when it expires anyway.
//   - The list only grows. Entries for certificates that have expired could be
//     pruned; they are kept because the list is small and a deny list that
//     forgets is a deny list that has to be reasoned about.
//   - It is not a replacement for rotating the CA if the CA key itself leaks.
//     If that happens, every certificate is worthless and the fix is a new CA
//     and a re-enrolment of every agent.
package agentpki
