// Package localnode is how the panel knows which machine it is running on.
//
// VKAI Panel was built as a control plane: the panel in one place, agents on
// other machines, every operation carried over mutual TLS. That is right for a
// fleet and wrong for the first five minutes, because it leaves the machine the
// panel was just installed on managing nothing - not even itself. This package
// is the missing half: it identifies the panel host, measures it, and gives the
// layers above a way to prove that a row in the servers table really is this
// machine before anyone runs a local command on that belief.
//
// # The identity
//
// A managed node is keyed on a node id: a UUID generated once, on first
// registration, and persisted at <EtcRoot>/node.json with mode 0600. It is the
// primary key of the node's row in the servers table.
//
// Hostnames and IP addresses were both rejected as the key because both change
// under a running installation - a rename, a new floating IP, a move between
// networks - and either would turn one node into two rows on the next
// registration. /etc/machine-id was rejected as the key for the opposite
// reason: it is stable, but it is not ours. It is absent in some minimal
// containers, it is regenerated by some cloud images on first boot, systemd
// documents it as a value that should not be exposed, and a cloned disk image
// carries a copy of it. A value the panel generates and owns has none of those
// properties.
//
// # The witness
//
// The node id alone answers "which node is this row", not "is this row the
// machine I am standing on". Restore a database onto a second machine and the
// row still says local. So the machine id is kept as a witness rather than as
// the key: a salted SHA-256 of /etc/machine-id (falling back to
// /var/lib/dbus/machine-id) is recorded both in node.json and in the database
// row, and the short path is offered only when the live value still agrees with
// both. The raw machine id is never written anywhere, which is why it is
// hashed.
//
// That pair covers the two ways the belief can go wrong:
//
//   - the database moves and the machine does not: the panel on the new machine
//     has its own node.json, so no row claims to be it;
//   - the machine is cloned and the database does not move: node.json comes
//     along, but the machine id underneath it does not, so the witness fails.
//
// When neither machine id file exists the witness cannot be formed. The panel
// then falls back to the node id alone and says so, rather than inventing a
// fingerprint that would prove nothing.
//
// # The facts
//
// Everything reported about the host is read from the running system - /proc,
// /etc/os-release, statfs, the interface table - and never from configuration
// an operator can get wrong. Anything that cannot be read is left unset, so it
// reaches the database as NULL. A null column is a fact the panel does not
// have; a plausible default would be a fact the panel is wrong about.
package localnode
